apiVersion: apps/v1
kind: Deployment
metadata:
  name: {SERVICE_NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate  # 部署策略为删除后重建，不使用默认的滚动更新
  selector:
    matchLabels:
      app: {SERVICE_NAME}
  template:
    metadata:
      labels:
        app: {SERVICE_NAME}
    spec:
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: app
        image: {DOCKER_IMAGE}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "50000Mi"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        env:
        - name: CONFIG
          valueFrom:
            configMapKeyRef:
              name: {SERVICE_NAME}
              key: env-conf  # 根据约定，使用 env-conf 作为配置文件的 key，通过环境变量注入配置
      imagePullSecrets:
          - name: regcred
      terminationGracePeriodSeconds: 600
