apiVersion: batch/v1
kind: Job
metadata:
  name: {SERVICE_NAME}
spec:
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: app
        image: {DOCKER_IMAGE}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "50000Mi"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        env:  # 这里通过将 configmap 以环境变量的方式注入容器的方式提供配置信息
        - name: CONFIG
          valueFrom:
            configMapKeyRef:
              name: {SERVICE_NAME}
              key: env-conf  # 根据约定，使用 env-conf 作为配置文件的 key
      imagePullSecrets:
          - name: regcred
      restartPolicy: Never
      terminationGracePeriodSeconds: 600
